//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelFilter
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public int MonthsToChange { get; set; }
        public System.DateTime ChangedDate { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string Description { get; set; }
        public int VehicleId { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
