//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Belts = new HashSet<Belt>();
            this.Brakes = new HashSet<Brake>();
            this.FuelFilters = new HashSet<FuelFilter>();
            this.Oils = new HashSet<Oil>();
            this.Shocks = new HashSet<Shock>();
            this.Tyres = new HashSet<Tyre>();
        }
    
        public int Id { get; set; }
        public int OwnerId { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public System.DateTime Year { get; set; }
        public int Mileage { get; set; }
        public int AverageMileage { get; set; }
        public string Color { get; set; }
        public decimal EngineDisplacement { get; set; }
        public int HorsePower { get; set; }
        public int Torque { get; set; }
        public int FuelType { get; set; }
        public string Description { get; set; }
        public int VehicleType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Belt> Belts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Brake> Brakes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuelFilter> FuelFilters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oil> Oils { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shock> Shocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tyre> Tyres { get; set; }
        public virtual User User { get; set; }
    }
}
