//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VehiclesDataEntities : DbContext
    {
        public VehiclesDataEntities()
            : base("name=VehiclesDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Belt> Belts { get; set; }
        public virtual DbSet<Brake> Brakes { get; set; }
        public virtual DbSet<FuelFilter> FuelFilters { get; set; }
        public virtual DbSet<Oil> Oils { get; set; }
        public virtual DbSet<Shock> Shocks { get; set; }
        public virtual DbSet<Tyre> Tyres { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
    }
}
